title: "Wanzi-Xiao"
email: xwz0611@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://Wanzi-Xiao.github.io/" 
github_username:  viiio-x

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
